messages:
  start: "üëã –ü—Ä–∏–≤–µ—Ç,  WebAvatar ‚Äî —ç—Ç–æ —Ç–≤–æ–π –¥—Ä—É–≥ –∏ –≤–µ—Ä–Ω—ã–π –ø–æ–º–æ—â–Ω–∏–∫ –Ω–∞ –≤—Å–µ —Å–ª—É—á–∞–∏ –∂–∏–∑–Ω–∏. –ú—ã —Å–æ–∑–¥–∞–ª–∏ –Ω–µ—Å–∫–æ–ª—å–∫–∏—Ö –ø–æ–º–æ—â–Ω–∏–∫–æ–≤, –∫–æ—Ç–æ—Ä—ã–µ –ø–æ–º–æ–≥—É—Ç —Ç–µ–±–µ –≤ —Ç–≤–æ–∏—Ö –ø–æ–≤—Å–µ–¥–Ω–µ–≤–Ω—ã—Ö –≤–æ–ø—Ä–æ—Å–∞—Ö). –ò–Ω–æ–≥–¥–∞ —Ö–æ—á–µ—Ç—Å—è –ø–æ–ª—É—á–∏—Ç—å –ø—Ä–∞–≤–∏–ª—å–Ω—ã–µ —Å–ª–æ–≤–∞ –∏ –ø–æ–¥–¥–µ—Ä–∂–∫—É, –∞ –∏–Ω–æ–≥–¥–∞ —Ö–æ—á–µ—Ç—Å—è —Ä–∞–∑—ã–≥—Ä–∞—Ç—å –¥—Ä—É–∑–µ–π –∏ –≤–º–µ—Å—Ç–µ –≤—Å–µ–º –ø–æ–≤–µ—Å–µ–ª–∏—Ç—å—Å—è, –¥–ª—è —ç—Ç–æ–≥–æ –º—ã –≤—Å–µ –∏ —Å–æ–∑–¥–∞–ª–∏,  —Å –ª—é–±–æ–≤—å—é —Ç–≤–æ—è –∫–æ–º–∞–Ω–¥–∞<a href="https://t.me/WebSindicat">WebSindicat</a> ‚ù§Ô∏è"

keyboard:
  add_profile: "–î–æ–±–∞–≤–∏—Ç—å –ø—Ä–æ—Ñ–∏–ª—å"
  edit_profile: "–†–µ–¥–∞–∫—Ç–∏—Ä–æ–≤–∞—Ç—å –ø—Ä–æ—Ñ–∏–ª—å"
